CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paper_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id),
    symbol          VARCHAR(20)   NOT NULL,
    side            VARCHAR(4)    NOT NULL,
    type            VARCHAR(8)    NOT NULL,
    status          VARCHAR(10)   NOT NULL,
    limit_price     NUMERIC(38,8),
    quantity        NUMERIC(38,8) NOT NULL,
    filled_quantity NUMERIC(38,8) NOT NULL DEFAULT 0,
    leverage        INT NOT NULL DEFAULT 10,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paper_fills (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL REFERENCES paper_orders(id),
    symbol      VARCHAR(20)   NOT NULL,
    side        VARCHAR(4)    NOT NULL,
    price       NUMERIC(38,8) NOT NULL,
    quantity    NUMERIC(38,8) NOT NULL,
    fee         NUMERIC(38,8) NOT NULL DEFAULT 0,
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paper_accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL UNIQUE REFERENCES users(id),
    cash_balance NUMERIC(38,8) NOT NULL,
    leverage     INT NOT NULL DEFAULT 10,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
